module P2PMessage
{
    class IPDestination
    {
        UInt16 port
        String address
    }

    class IPAddress
    {
        Int ip_type
        IPDestination local
        IPDestination remote
    }

    class Ping
    {
        String nodeid
        TimePoint stamp
        String signature
        IPAddress connection_info
    }

    class Pong
    {
        String nodeid
        TimePoint stamp
        String signature
    }

    class FindNode
    {
        String nodeid
    }

    class NodeDetails
    {
        String origin
        Array String nodeids
    }

    class IntroduceTo
    {
        String nodeid
    }

    class OpenConnectionWith
    {
        IPAddress addr
    }

    class Other
    {
        Extension contents
    }
}
////2
