class message_ip_destination
{
    port : int;
    address : string
};
class message_ip_address
{
    type : int;
    local : message_ip_destination;
    remote : message_ip_destination
};
class message_join
{
};
class message_drop
{
};
class message_ping
{
    nodeid : string
};
class message_pong
{
    nodeid : string
};
class message_error
{
};
class message_time_out
{
};
class message_get_peers
{
    nodeid : string
};
class message_peer_info
{
    nodeid : string;
    address : message_ip_address
}
