module Data2
{
    class Number
    {
        UInt64 value
    }

    class Index
    {
        Hash String String dictionary
    }

    class FileData
    {
        Hash String Extension block
    }

    class FileData2
    {
        Hash UInt64 Extension block
    }
}
