module Data
{
    class StringValue
    {
        String value
    }

    class UInt64Value
    {
        uint64_t value
    }

    class StringBlockItem
    {
        String key
        Extension item
    }

    class UInt64BlockItem
    {
        UInt64 key
        Extension item
    }
}
////1
