module Data2
{
    class Number
    {
        UInt64 value
    }

    class Index
    {
        Hash String String dictionary
    }

    class FileData
    {
        Hash String Extension block
    }

    class FileData2
    {
        Hash UInt64 Extension block
    }

    class BlockRow
    {
        String key
        Extension item
    }

    class BlockRow2
    {
        UInt64 index
        Extension item
    }
}
////2
